import { useState } from 'react'
import './App.css'

function App() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    message: ''
  })

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    })
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    alert('Thank you for your inquiry! We will get back to you soon.')
    setFormData({ name: '', email: '', phone: '', message: '' })
  }

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <div className="container">
          <div className="logo">
            <span className="logo-icon">☀️</span>
            <span className="logo-text">Regain Energies</span>
          </div>
          <nav className="nav">
            <a href="#about">About Us</a>
            <a href="#challenge">Challenge</a>
            <a href="#opportunities">Opportunities</a>
            <a href="#approach">Our Approach</a>
            <a href="#plan">Plan</a>
            <a href="#collaborations">Collaborations</a>
            <a href="#contact">Contact</a>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="hero">
        <div className="hero-overlay"></div>
        <div className="hero-content">
          <h1>Regain Energies Solutions Pvt. Ltd.</h1>
          <p>Pioneering Solar Panel Recycling for a Sustainable Future</p>
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="section about">
        <div className="container">
          <h2>About Us</h2>
          <div className="about-wrapper">
            <div className="about-image">
              <img 
                src="https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80" 
                alt="Solar panels in a field"
              />
            </div>
            <div className="about-text">
              <p>
                Regain Energies Pvt. Ltd. is a pioneering company in the field of solar panel recycling,
                spearheading efforts in sustainable and environmentally conscious disposal and recycling of
                solar panels. We are committed to addressing the critical issue of e-waste generated by solar
                panels, providing innovative and efficient solutions to recycle these materials responsibly.
              </p>
              <p>
                We focus on the development and implementation of advanced technologies and processes to extract
                valuable materials from end-of-life solar panels while minimizing environmental impact. This
                commitment to sustainability aligns with the growing global emphasis on green energy and the
                circular economy.
              </p>
              <p>
                By specializing in solar panel recycling, we contribute significantly to reducing the ecological
                footprint of renewable energy technologies, ensuring that the transition to solar power remains
                environmentally friendly throughout the entire lifecycle of the panels.
              </p>
            </div>
          </div>
          
          <div className="importance-section">
            <h3>Importance of addressing PV recycling in the context of renewable energy goals</h3>
            <div className="importance-grid">
              <div className="importance-card">
                <img src="https://images.unsplash.com/photo-1569163139599-0f4517e36f51?w=300&q=80" alt="Earth" />
                <h4>Environmental Responsibility</h4>
              </div>
              <div className="importance-card">
                <img src="https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=300&q=80" alt="E-waste" />
                <h4>E-Waste Mitigation</h4>
              </div>
              <div className="importance-card">
                <img src="https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=300&q=80" alt="Resources" />
                <h4>Resource Conservation</h4>
              </div>
              <div className="importance-card">
                <img src="https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=300&q=80" alt="Circular economy" />
                <h4>Circular Economy Approach</h4>
              </div>
              <div className="importance-card">
                <img src="https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=300&q=80" alt="Sustainable growth" />
                <h4>Supporting Sustainable Growth</h4>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Challenge Section */}
      <section id="challenge" className="section challenge">
        <div className="container">
          <h2>Challenge</h2>
          <div className="challenge-header">
            <img 
              src="https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80" 
              alt="Environmental challenges"
              className="challenge-hero-img"
            />
            <h3>Our Services Environmental Challenges</h3>
            <p>
              Hydrotech redefines your relationship with energy. Save money. Minimize your carbon footprint. 
              Take control of your power costs today!
            </p>
          </div>
          <div className="challenge-grid">
            <div className="challenge-card">
              <img src="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80" alt="E-waste" />
              <h4>E-Waste Volume and Composition</h4>
              <p>Foresee the pain and trouble that we are bounds to ensue equal blame belongs to their duty...</p>
            </div>
            <div className="challenge-card">
              <img src="https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=400&q=80" alt="Landfill" />
              <h4>Landfill Contamination and Soil Pollution</h4>
              <p>Foresee the pain and trouble that we are bounds to ensue equal blame belongs to their duty...</p>
            </div>
            <div className="challenge-card">
              <img src="https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=80" alt="Energy" />
              <h4>Resource Depletion and Energy Consumption</h4>
              <p>Foresee the pain and trouble that we are bounds to ensue equal blame belongs to their duty...</p>
            </div>
            <div className="challenge-card">
              <img src="https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=400&q=80" alt="Emissions" />
              <h4>Greenhouse Gas Emissions</h4>
              <p>Foresee the pain and trouble that we are bounds to ensue equal blame belongs to their duty...</p>
            </div>
            <div className="challenge-card">
              <img src="https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80" alt="Recycling" />
              <h4>Complex Recycling Challenges</h4>
              <p>Foresee the pain and trouble that we are bounds to ensue equal blame belongs to their duty...</p>
            </div>
          </div>
        </div>
      </section>

      {/* Opportunities Section */}
      <section id="opportunities" className="section opportunities">
        <div className="container">
          <h2>Opportunities</h2>
          <div className="opportunities-header">
            <span className="highlight-badge">Highlights</span>
            <h3>Economic Opportunities</h3>
            <p>For creating value and pursuing economic avenues</p>
          </div>
          <div className="opportunities-grid">
            <div className="opportunity-card">
              <img src="https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=400&q=80" alt="Circular economy" />
              <h4>Resource Recovery and Circular Economy</h4>
              <p>
                End-of-life solar panels contain valuable materials like silicon, glass, aluminum, and rare earth elements. 
                Proper recycling processes enable the recovery and reuse of these materials, fostering a circular economy.
              </p>
            </div>
            <div className="opportunity-card">
              <img src="https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&q=80" alt="Innovation" />
              <h4>Innovation and Technological Advancements</h4>
              <p>
                The need for efficient recycling methods has spurred innovation in the field of PV waste management. 
                Companies investing in R&D create opportunities for breakthroughs.
              </p>
            </div>
            <div className="opportunity-card">
              <img src="https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400&q=80" alt="Jobs" />
              <h4>Job Creation and Economic Growth</h4>
              <p>
                The solar panel recycling industry generates employment opportunities across various sectors, including 
                recycling facilities, research and development, logistics, and more.
              </p>
            </div>
            <div className="opportunity-card">
              <img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80" alt="Market" />
              <h4>Market Expansion and Sustainability Services</h4>
              <p>
                With an increasing focus on sustainability, businesses and governments seek services that align with 
                responsible waste management and recycling.
              </p>
            </div>
            <div className="opportunity-card">
              <img src="https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&q=80" alt="Collaboration" />
              <h4>Value Chain Integration and Collaboration</h4>
              <p>
                Solar panel recycling necessitates collaboration across the entire value chain, from manufacturers to 
                recyclers and policymakers.
              </p>
            </div>
            <div className="opportunity-card">
              <img src="https://images.unsplash.com/photo-1536939459926-301728717817?w=400&q=80" alt="Transformation" />
              <h4>Waste-to-Resource Transformation</h4>
              <p>
                Recycling PV waste transforms what was once considered waste into valuable resources, creating 
                secondary raw materials for various industries.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Our Approach Section */}
      <section id="approach" className="section approach">
        <div className="container">
          <h2>Our Approach</h2>
          <p className="approach-subtitle">What we do with existing panels, including premature breakage</p>
          <div className="approach-image">
            <img 
              src="https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1000&q=80" 
              alt="Solar panel recycling process"
            />
          </div>
          <div className="approach-timeline">
            <div className="approach-step">
              <div className="step-number">1</div>
              <div className="step-content">
                <img src="https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=80" alt="Collection" />
                <h4>Collection and Assessment</h4>
                <p>
                  We collect end-of-life or damaged solar panels from various sources, including manufacturers and 
                  Developers. The company conducts an assessment to determine the condition and level of damage.
                </p>
              </div>
            </div>
            <div className="approach-step">
              <div className="step-number">2</div>
              <div className="step-content">
                <img src="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80" alt="Sorting" />
                <h4>Sorting and Segregation</h4>
                <p>
                  Panels are sorted based on their condition and damage severity. Panels with premature breakage, 
                  defects, or irreparable damage are segregated for appropriate processing.
                </p>
              </div>
            </div>
            <div className="approach-step">
              <div className="step-number">3</div>
              <div className="step-content">
                <img src="https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80" alt="Recovery" />
                <h4>Material Recovery and Recycling</h4>
                <p>
                  We employ specialized recycling processes to recover valuable materials from these damaged or 
                  end-of-life panels. This includes Material Extraction, Resource Reclamation & Environmental Compliance.
                </p>
              </div>
            </div>
            <div className="approach-step">
              <div className="step-number">4</div>
              <div className="step-content">
                <img src="https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&q=80" alt="Reuse" />
                <h4>Reuse and Repurposing</h4>
                <p>
                  Salvageable components or materials are often refurbished or repurposed for use in various industries, 
                  reducing the demand for virgin resources and promoting a circular economy.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Plan Section */}
      <section id="plan" className="section plan">
        <div className="container">
          <h2>Plan</h2>
          <div className="section-content">
            <p>Content coming soon...</p>
          </div>
        </div>
      </section>

      {/* Collaborations Section */}
      <section id="collaborations" className="section collaborations">
        <div className="container">
          <h2>Collaborations</h2>
          <div className="section-content">
            <p>Content coming soon...</p>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="section contact">
        <div className="container">
          <h2>Contact</h2>
          <div className="contact-wrapper">
            <div className="contact-image">
              <img 
                src="https://images.unsplash.com/photo-1423666639041-f56000c27a9a?w=600&q=80" 
                alt="Contact us"
              />
            </div>
            <form className="contact-form" onSubmit={handleSubmit}>
              <div className="form-group">
                <label htmlFor="name">Name</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  required
                  placeholder="Your Name"
                />
              </div>
              <div className="form-group">
                <label htmlFor="email">Email</label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  required
                  placeholder="your@email.com"
                />
              </div>
              <div className="form-group">
                <label htmlFor="phone">Phone</label>
                <input
                  type="tel"
                  id="phone"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="Your Phone Number"
                />
              </div>
              <div className="form-group">
                <label htmlFor="message">Message</label>
                <textarea
                  id="message"
                  name="message"
                  value={formData.message}
                  onChange={handleChange}
                  required
                  placeholder="Your message..."
                  rows="5"
                />
              </div>
              <button type="submit" className="submit-button">Send Message</button>
            </form>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container">
          <p>© 2026 Regain Energies Solutions Pvt. Ltd. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

export default App
